spring:
  application:
    name: bumentong

  datasource:
      url: jdbc:mysql://127.0.0.1:3306/bumentong
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB


aliyun:
  oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucketName: spring233
      region: cn-beijing


token:
  secret: bumentongtokenkkkddd
  expiration: 86400000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

